image: condaforge/mambaforge:latest

stages:
  - test

variables:
  PYVERSION: "3.8"
  BINPATH: "/root/rsmenv/bin"
  CODECOV_TOKEN: "488304b7-b1c5-4fc7-bfb6-9e7cbcb36a08"

# set up basic job
.runtests:
  before_script:
    - "mamba create --prefix /root/rsmenv -c conda-forge -c ets --file requirements.txt python=${PYVERSION} --yes"
    - /root/rsmenv/bin/pip install -e .
    - echo "import os" > sitecustomize.py
    - echo "try:" >> sitecustomize.py
    - echo "    import coverage" >> sitecustomize.py
    - echo "    os.environ['COVERAGE_PROCESS_START'] = '.coveragerc'" >> sitecustomize.py
    - echo "    coverage.process_startup()" >> sitecustomize.py
    - echo "except ImportError:" >> sitecustomize.py
    - echo "    pass" >> sitecustomize.py
  script:
    - "/root/rsmenv/bin/nose2 -s tests ${TESTFILES}"
  after_script:
    - /root/rsmenv/bin/codecov

# first set of test files
testset1:
  extends: ".runtests"
  variables:
    TESTFILES: "test_experiment_rsmtool_1"
  stage: "test"

# second set of test files
testset2:
  extends: ".runtests"
  variables:
    TESTFILES: "test_comparer test_configuration_parser test_experiment_rsmtool_2 test_wandb"
  stage: "test"

# third set of test files
testset3:
  extends: ".runtests"
  variables:
    TESTFILES: "test_analyzer test_experiment_rsmeval test_fairness_utils test_utils_prmse test_container test_test_utils test_cli"
  stage: "test"

# fourth set of test files
testset4:
  extends: ".runtests"
  variables:
    TESTFILES: "test_experiment_rsmcompare test_experiment_rsmsummarize test_modeler test_preprocessor test_writer test_experiment_rsmtool_3"
  stage: "test"

# fifth set of test files
testset5:
  extends: ".runtests"
  variables:
    TESTFILES: "test_experiment_rsmpredict test_reader test_reporter test_transformer test_utils test_experiment_rsmtool_4"
  stage: "test"

# sixth set of test files
testset6:
  extends: ".runtests"
  variables:
    TESTFILES: "test_experiment_rsmxval test_experiment_rsmexplain test_explanation_utils"
  stage: "test"
