image: continuumio/miniconda3:latest

stages:
  - test

variables:
  PYVERSION: "3.8"
  BINPATH: "/root/rsmenv/bin"
  CODECOV_TOKEN: "488304b7-b1c5-4fc7-bfb6-9e7cbcb36a08"

# set up basic job
.runtests:
  before_script:
    - "conda create --prefix /root/rsmenv -c conda-forge -c ets --file requirements.txt python=${PYVERSION} --yes --quiet"
    - /root/rsmenv/bin/pip install -e .
    - echo "import os" > sitecustomize.py
    - echo "try:" >> sitecustomize.py
    - echo "    import coverage" >> sitecustomize.py
    - echo "    os.environ['COVERAGE_PROCESS_START'] = '.coveragerc'" >> sitecustomize.py
    - echo "    coverage.process_startup()" >> sitecustomize.py
    - echo "except ImportError:" >> sitecustomize.py
    - echo "    pass" >> sitecustomize.py
  script:
    - "/root/rsmenv/bin/nosetests --nologcapture --with-coverage --cover-package=rsmtool ${TESTFILES}"
  after_script:
    - /root/rsmenv/bin/codecov

# first set of test files
testset1:
  extends: ".runtests"
  variables:
    TESTFILES: "tests/test_experiment_rsmtool_1.py"
  stage: "test"

# second set of test files
testset2:
  extends: ".runtests"
  variables:
    TESTFILES: "tests/test_comparer.py tests/test_configuration_parser.py tests/test_experiment_rsmtool_2.py"
  stage: "test"

# third set of test files
testset3:
  extends: ".runtests"
  variables:
    TESTFILES: "tests/test_analyzer.py tests/test_experiment_rsmeval.py tests/test_fairness_utils.py tests/test_utils_prmse.py tests/test_container.py tests/test_test_utils.py tests/test_cli.py"
  stage: "test"

# fourth set of test files
testset4:
  extends: ".runtests"
  variables:
    TESTFILES: "tests/test_experiment_rsmcompare.py tests/test_experiment_rsmsummarize.py tests/test_modeler.py tests/test_preprocessor.py tests/test_writer.py tests/test_experiment_rsmtool_3.py"
  stage: "test"

# fifth set of test files
testset5:
  extends: ".runtests"
  variables:
    TESTFILES: "tests/test_experiment_rsmpredict.py tests/test_reader.py tests/test_reporter.py tests/test_transformer.py tests/test_utils.py tests/test_experiment_rsmtool_4.py"
  stage: "test"

# sixth set of test files
testset6:
  extends: ".runtests"
  variables:
    TESTFILES: "tests/test_experiment_rsmxval.py tests/test_experiment_rsmexplain.py tests/test_explanation_utils.py"
  stage: "test"
