# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more git_hooks

repos:
-   repo: https://github.com/ikamensh/flynt/
    rev: '0.69'
    hooks:
    -   id: flynt
-   repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
    -   id: black
