language: python
python:
  - 3.4
notifications:
  email: false
  slack: etsnlp:TLmcZ7JGkPMv5eEpGxUuFm5k

# run on the new Travis infrastructure
sudo: false

# Install stuff
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda config --add channels desilinguist
  - conda update --yes conda
install:
  - conda install --yes python=3.4 rsmtool
  - python setup.py install

# Run test
script:
  - nosetests -v ${TRAVIS_BUILD_DIR}/${TRAVIS_REPO_SLUG}/tests

