language: python
python:
  - 3.4
notifications:
  email: false
  slack: etsnlp:TLmcZ7JGkPMv5eEpGxUuFm5k

# run on the new Travis infrastructure
sudo: false

# Install stuff
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda config --add channels desilinguist
  - conda update --yes conda
install:
  - conda install --yes ${TRAVIS_BUILD_DIR}/conda_requirements.txt
  - python setup.py install

# Run test
script:
  - echo $PYTHONPATH
  - python -c 'import sys; print(sys.path)'
  - python -c 'import numpy; print(numpy.__version__); print(numpy.__file__)'
  - python -c 'import matplotlib; print(matplotlib.__version__); print(matplotlib.__file__)'
  - python -c 'import matplotlib.pyplot as plt; print(plt.__spec__)'
  - python -c 'from matplotlib import numpy as mnp; print(mnp.__version__)'
  - python -c 'import IPython; print(IPython.sys_info())'
  - nosetests -v ${TRAVIS_BUILD_DIR}/tests/test_experiment.py:test_run_experiment_lr
