language: python
python:
  - 3.4
notifications:
  email: false
  slack: etsnlp:TLmcZ7JGkPMv5eEpGxUuFm5k

# run on the new Travis infrastructure
sudo: false

# Install stuff
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda config --add channels desilinguist
  - conda update --yes conda
install:
  - conda install --file conda_requirements.txt --yes
  - pip install -e .

# Run test
script:
  - nosetests -v tests/test_experiment.py:test_run_experiment_lr
