# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

variables:
  MPLBACKEND: Agg

trigger:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string

jobs:

- job: 'RSMToolTests'
  pool:
    vmImage: 'windows-latest'
  strategy:
    parallel: 5

  steps:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - script: |
      conda update --quiet --yes conda
      conda info -a
    displayName: "Update conda"

  - script: |
      conda create --name rsmdev --yes --quiet -c conda-forge -c defaults python=%PYTHON_VERSION% numpy=1.17 nose --file requirements.txt
      conda init cmd.exe
      CALL activate rsmdev
      pip install -e .
    displayName: 'Install dependencies & code'

  - powershell: ./DistributeTests.ps1 
    displayName: 'PowerShell Script to distribute tests'

  - script: |
      CALL activate rsmdev
      echo $(pytestfiles)
      nosetests --with-xunit $(pytestfiles)
    displayName: 'Run tests'
    continueOnError: true

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testResultsFiles: 'nosetests.xml'
      testRunTitle: 'RSMTool tests'
    condition: succeededOrFailed()