channels:
  - defaults
  - conda-forge
  - desilinguist
dependencies:
- python==3.6.3
- ipython=6.3.1
- jupyter=1.0.0
- joblib=0.11
- matplotlib=2.1.2
- nose=1.3.7
- notebook=5.4.1
- numpy=1.13.3
- pandas=0.22.0
- scikit-learn=0.19.1
- scipy=1.0.0
- seaborn=0.8.1
- skll=1.5.2
- statsmodels=0.8.0
- parameterized
- zeromq
- sphinx
- sphinx_rtd_theme
- coverage
- setuptools
- openpyxl
- xlrd
- xlwt
