channels:
  - defaults
  - desilinguist
dependencies:
- python==3.4.5
- ipython=5.1.0
- jupyter=1.0.0
- joblib=0.9.4
- matplotlib=2.0.0
- nose=1.3.7
- notebook=4.3.1
- numpy=1.11.3
- pandas=0.19.2
- scikit-learn=0.18.1
- scipy=0.18.1
- seaborn=0.7.1
- skll=1.3
- statsmodels=0.6.1
- zeromq
- sphinx
- sphinx_rtd_theme
- coverage
- setuptools
- openpyxl
- xlrd
- xlwt
