channels:
  - defaults
  - conda-forge
  - desilinguist
dependencies:
  - python=3.6.8
  - ipython=6.5.0
  - jupyter=1.0.0
  - joblib=0.11
  - matplotlib=2.1.2
  - nose=1.3.7
  - notebook=5.7.2
  - numpy
  - pandas
  - scipy
  - seaborn
  - skll=1.5.2
  - statsmodels
  - coverage
  - openpyxl
  - parameterized
  - setuptools
  - sphinx
  - sphinx_rtd_theme
  - xlrd
  - xlwt