channels:
  - conda-forge
  - desilinguist
dependencies:
  - python
  - ipython
  - jupyter
  - joblib
  - matplotlib
  - nose
  - notebook
  - numpy
  - pandas=0.23.4
  - scipy
  - seaborn
  - skll=1.5.2
  - statsmodels
  - coverage
  - openpyxl
  - parameterized
  - sphinx
  - sphinx_rtd_theme
  - xlrd
  - xlwt
