channels:
  - conda-forge
  - desilinguist
dependencies:
  - python=3.6.8
  - ipython=7.9.0
  - jupyter=1.0.0
  - joblib=0.14.0
  - matplotlib=3.1.2
  - nose=1.3.7
  - notebook=6.0.1
  - numpy=1.14.6
  - pandas=0.23.4
  - scipy=1.1.0
  - seaborn=0.9.0
  - skll=1.5.2
  - statsmodels=0.10.1
  - coverage
  - openpyxl
  - parameterized
  - setuptools
  - sphinx
  - sphinx_rtd_theme
  - xlrd
  - xlwt
