channels:
  - conda-forge
  - desilinguist
dependencies:
  - python=3.6
  - ipython=7.9.0
  - matplotlib=3.1.2
  - notebook=6.0.1
  - numpy=1.14.6
  - pandas=0.23.4
  - scipy=1.1.0
  - skll=1.5.2
  - statsmodels=0.10.1
