On branch 597-add-wandb-rsmeval
Your branch is up to date with 'origin/597-add-wandb-rsmeval'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   tests/data/output/autogenerated_rsmeval_config.json
	modified:   tests/data/output/autogenerated_rsmeval_config_groups.json
	modified:   tests/data/output/interactive_rsmeval_config_groups.json

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.log.test
	s
	tests/data/experiments/linearsvr-self-summary/output/model_comparison_eval_short.csv
	tests/data/experiments/linearsvr-self-summary/output/model_comparison_margcor_score_all_data.csv
	tests/data/experiments/linearsvr-self-summary/output/model_comparison_pcor_score_all_data.csv
	tests/data/experiments/lr-eval-system-score-constant/output/lr_eval_system_score_constant_estimates_csd_by_L1.csv
	tests/data/experiments/lr-eval-system-score-constant/output/lr_eval_system_score_constant_estimates_csd_by_QUESTION.csv
	tests/data/experiments/lr-eval-system-score-constant/output/lr_eval_system_score_constant_estimates_osa_by_L1.csv
	tests/data/experiments/lr-eval-system-score-constant/output/lr_eval_system_score_constant_estimates_osa_by_QUESTION.csv
	tests/data/experiments/lr-eval-system-score-constant/output/lr_eval_system_score_constant_estimates_osd_by_L1.csv
	tests/data/experiments/lr-eval-system-score-constant/output/lr_eval_system_score_constant_estimates_osd_by_QUESTION.csv
	tests/data/experiments/lr-eval-system-score-constant/output/lr_eval_system_score_constant_fairness_metrics_by_L1.csv
	tests/data/experiments/lr-eval-system-score-constant/output/lr_eval_system_score_constant_fairness_metrics_by_QUESTION.csv
	tests/data/experiments/lr-self-eval-summary/output/model_comparison_betas.csv
	tests/data/experiments/lr-self-eval-summary/output/model_comparison_eval_short.csv
	tests/data/experiments/lr-self-eval-summary/output/model_comparison_margcor_score_all_data.csv
	tests/data/experiments/lr-self-eval-summary/output/model_comparison_model_fit.csv
	tests/data/experiments/lr-self-eval-summary/output/model_comparison_pcor_score_all_data.csv
	tests/data/experiments/lr-self-summary-dict/output/model_comparison_betas.csv
	tests/data/experiments/lr-self-summary-dict/output/model_comparison_eval_short.csv
	tests/data/experiments/lr-self-summary-dict/output/model_comparison_margcor_score_all_data.csv
	tests/data/experiments/lr-self-summary-dict/output/model_comparison_model_fit.csv
	tests/data/experiments/lr-self-summary-dict/output/model_comparison_pcor_score_all_data.csv
	tests/data/experiments/lr-self-summary-no-scaling/output/model_comparison_betas.csv
	tests/data/experiments/lr-self-summary-no-scaling/output/model_comparison_eval_short.csv
	tests/data/experiments/lr-self-summary-no-scaling/output/model_comparison_margcor_score_all_data.csv
	tests/data/experiments/lr-self-summary-no-scaling/output/model_comparison_model_fit.csv
	tests/data/experiments/lr-self-summary-no-scaling/output/model_comparison_pcor_score_all_data.csv
	tests/data/experiments/lr-self-summary-no-trim/output/model_comparison_betas.csv
	tests/data/experiments/lr-self-summary-no-trim/output/model_comparison_eval_short.csv
	tests/data/experiments/lr-self-summary-no-trim/output/model_comparison_margcor_score_all_data.csv
	tests/data/experiments/lr-self-summary-no-trim/output/model_comparison_model_fit.csv
	tests/data/experiments/lr-self-summary-no-trim/output/model_comparison_pcor_score_all_data.csv
	tests/data/experiments/lr-self-summary-object/output/model_comparison_betas.csv
	tests/data/experiments/lr-self-summary-object/output/model_comparison_eval_short.csv
	tests/data/experiments/lr-self-summary-object/output/model_comparison_margcor_score_all_data.csv
	tests/data/experiments/lr-self-summary-object/output/model_comparison_model_fit.csv
	tests/data/experiments/lr-self-summary-object/output/model_comparison_pcor_score_all_data.csv
	tests/data/experiments/lr-self-summary-with-custom-sections/output/model_comparison_betas.csv
	tests/data/experiments/lr-self-summary-with-custom-sections/output/model_comparison_model_fit.csv
	tests/data/experiments/lr-self-summary-with-h2/output/model_comparison_betas.csv
	tests/data/experiments/lr-self-summary-with-h2/output/model_comparison_eval_short.csv
	tests/data/experiments/lr-self-summary-with-h2/output/model_comparison_margcor_score_all_data.csv
	tests/data/experiments/lr-self-summary-with-h2/output/model_comparison_model_fit.csv
	tests/data/experiments/lr-self-summary-with-h2/output/model_comparison_pcor_score_all_data.csv
	tests/data/experiments/lr-self-summary-with-h2/output/model_comparison_true_score_eval.csv
	tests/data/experiments/lr-self-summary-with-tsv-inputs/output/model_comparison_betas.csv
	tests/data/experiments/lr-self-summary-with-tsv-inputs/output/model_comparison_eval_short.csv
	tests/data/experiments/lr-self-summary-with-tsv-inputs/output/model_comparison_margcor_score_all_data.csv
	tests/data/experiments/lr-self-summary-with-tsv-inputs/output/model_comparison_model_fit.csv
	tests/data/experiments/lr-self-summary-with-tsv-inputs/output/model_comparison_pcor_score_all_data.csv
	tests/data/experiments/lr-self-summary-with-tsv-output/output/model_comparison_betas.tsv
	tests/data/experiments/lr-self-summary-with-tsv-output/output/model_comparison_eval_short.tsv
	tests/data/experiments/lr-self-summary-with-tsv-output/output/model_comparison_margcor_score_all_data.tsv
	tests/data/experiments/lr-self-summary-with-tsv-output/output/model_comparison_model_fit.tsv
	tests/data/experiments/lr-self-summary-with-tsv-output/output/model_comparison_pcor_score_all_data.tsv
	tests/data/experiments/lr-self-summary-with-xlsx-output/output/model_comparison_betas.xlsx
	tests/data/experiments/lr-self-summary-with-xlsx-output/output/model_comparison_eval_short.xlsx
	tests/data/experiments/lr-self-summary-with-xlsx-output/output/model_comparison_margcor_score_all_data.xlsx
	tests/data/experiments/lr-self-summary-with-xlsx-output/output/model_comparison_model_fit.xlsx
	tests/data/experiments/lr-self-summary-with-xlsx-output/output/model_comparison_pcor_score_all_data.xlsx
	tests/data/experiments/lr-self-summary/output/model_comparison_betas.csv
	tests/data/experiments/lr-self-summary/output/model_comparison_eval_short.csv
	tests/data/experiments/lr-self-summary/output/model_comparison_margcor_score_all_data.csv
	tests/data/experiments/lr-self-summary/output/model_comparison_model_fit.csv
	tests/data/experiments/lr-self-summary/output/model_comparison_pcor_score_all_data.csv
	tests/data/experiments/summary-with-custom-names/output/model_comparison_betas.csv
	tests/data/experiments/summary-with-custom-names/output/model_comparison_eval_short.csv
	tests/data/experiments/summary-with-custom-names/output/model_comparison_margcor_score_all_data.csv
	tests/data/experiments/summary-with-custom-names/output/model_comparison_model_fit.csv
	tests/data/experiments/summary-with-custom-names/output/model_comparison_pcor_score_all_data.csv
	tests/data/experiments/wandb/output/

no changes added to commit (use "git add" and/or "git commit -a")
