package:
  name: rsmtool
  version: 5.2.0

source:
  path: ../../../../rsmtool

build:
  number: 0
  script:
    - cd $SRC_DIR
    - $PYTHON setup.py install
  entry_points:
    - rsmtool = rsmtool.rsmtool:main
    - rsmcompare = rsmtool.rsmcompare:main
    - rsmeval = rsmtool.rsmeval:main
    - rsmpredict = rsmtool.rsmpredict:main
    - rsmsummarize = rsmtool.rsmsummarize:main
    - render_notebook = rsmtool.report:main

requirements:
  build:
    - python
    - numpy 1.10.4
    - scipy 0.17.0
    - ipython 4.2.0
    - jupyter 1.0.0
    - joblib 0.9.4
    - matplotlib 1.5.1
    - nose 1.3.7
    - notebook 4.2.2
    - pandas 0.18.0
    - scikit-learn 0.17.1
    - seaborn 0.7.0
    - skll 1.2.1
    - statsmodels 0.6.1
    - zeromq 4.1.3
    - setuptools
    - nomkl

  run:
    - python
    - numpy 1.10.4
    - scipy 0.17.0
    - ipython 4.2.0
    - jupyter 1.0.0
    - joblib 0.9.4
    - matplotlib 1.5.1
    - nose 1.3.7
    - notebook 4.2.2
    - pandas 0.18.0
    - scikit-learn 0.17.1
    - seaborn 0.7.0
    - skll 1.2.1
    - statsmodels 0.6.1
    - zeromq 4.1.3
    - nomkl

test:
  # Python imports
  imports:
    - rsmtool
    - rsmtool.analysis
    - rsmtool.comparison
    - rsmtool.create_features
    - rsmtool.input
    - rsmtool.model
    - rsmtool.predict
    - rsmtool.preprocess
    - rsmtool.report
    - rsmtool.utils
    - rsmtool.test_utils

  commands:
    - rsmtool --help
    - rsmeval --help
    - rsmcompare --help
    - rsmpredict --help
    - render_notebook --help

about:
  home: https://github.com/EducationalTestingService/rsmtool
  license: Apache 2.0
