{% set data = load_setup_py_data() %}

package:
  name: rsmtool
  version: 6.1.0

source:
  path: ../../../rsmtool

build:
  number: 0
  script:
    - cd $SRC_DIR
    - $PYTHON setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - rsmtool = rsmtool.rsmtool:main
    - rsmcompare = rsmtool.rsmcompare:main
    - rsmeval = rsmtool.rsmeval:main
    - rsmpredict = rsmtool.rsmpredict:main
    - rsmsummarize = rsmtool.rsmsummarize:main
    - render_notebook = rsmtool.reporter:main
    - convert_feature_json = rsmtool.convert_feature_json:main


{% block requirements -%}
requirements:
  build:
    - python
    {% for req in data.get('install_requires', []) -%}
    - {{(req.replace(">", " >") if ">" in req else req.replace("==", " "))}}
    {% endfor %}
  run:
    - python
    {% for req in data.get('install_requires', []) -%}
    - {{(req.replace(">", " >") if ">" in req else req.replace("==", " "))}}
    {% endfor %}
{%- endblock %}

test:
  # Python imports
  imports:
    - rsmtool
    - rsmtool.analyzer
    - rsmtool.comparer
    - rsmtool.configuration_parser
    - rsmtool.container
    - rsmtool.convert_feature_json
    - rsmtool.modeler
    - rsmtool.preprocessor
    - rsmtool.reader
    - rsmtool.reporter
    - rsmtool.test_utils
    - rsmtool.transformer
    - rsmtool.utils
    - rsmtool.writer

  commands:
    - rsmtool --help
    - rsmeval --help
    - rsmcompare --help
    - rsmpredict --help
    - rsmsummarize --help
    - render_notebook --help
    - convert_feature_json --help

about:
  home: https://github.com/EducationalTestingService/rsmtool
  license: Apache 2.0
