package:
  name: rsmtool
  version: 11.0.1

source:
  path: ../../../rsmtool

build:
  number: 0
  noarch: python
  script:
    - cd $SRC_DIR
    - "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - rsmtool = rsmtool.rsmtool:main
    - rsmcompare = rsmtool.rsmcompare:main
    - rsmeval = rsmtool.rsmeval:main
    - rsmpredict = rsmtool.rsmpredict:main
    - rsmsummarize = rsmtool.rsmsummarize:main
    - rsmxval = rsmtool.rsmxval:main
    - rsmexplain = rsmtool.rsmexplain:main
    - render_notebook = rsmtool.reporter:main
    - convert_feature_json = rsmtool.convert_feature_json:main

requirements:
  build:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python
    - jupyter
    - ipython
    - notebook
    - numpy
    - openpyxl
    - pandas
    - seaborn
    - skll==4.0.0
    - statsmodels
    - tqdm
    - xlrd
    - xlwt
    - shap==0.42.1

test:
  # Python imports
  imports:
    - rsmtool
    - rsmtool.analyzer
    - rsmtool.comparer
    - rsmtool.configuration_parser
    - rsmtool.container
    - rsmtool.convert_feature_json
    - rsmtool.fairness_utils
    - rsmtool.modeler
    - rsmtool.preprocessor
    - rsmtool.reader
    - rsmtool.reporter
    - rsmtool.test_utils
    - rsmtool.transformer
    - rsmtool.utils
    - rsmtool.writer

  commands:
    - rsmtool --help
    - rsmeval --help
    - rsmcompare --help
    - rsmpredict --help
    - rsmsummarize --help
    - rsmxval --help
    - rsmexplain --help
    - render_notebook --help
    - convert_feature_json --help

about:
  home: https://github.com/EducationalTestingService/rsmtool
  license: Apache-2.0
  license_file: LICENSE
