package:
  name: rsmtool
  version: 6.1.0

source:
  path: ../../../rsmtool

build:
  number: 0
  script:
    - cd $SRC_DIR
    - $PYTHON setup.py install
  entry_points:
    - rsmtool = rsmtool.rsmtool:main
    - rsmcompare = rsmtool.rsmcompare:main
    - rsmeval = rsmtool.rsmeval:main
    - rsmpredict = rsmtool.rsmpredict:main
    - rsmsummarize = rsmtool.rsmsummarize:main
    - render_notebook = rsmtool.reporter:main
    - convert_feature_json = rsmtool.convert_feature_json:main

requirements:
  build:
    - python
    - numpy>=1.14.0,<1.15
    - scipy>=1.1.0,<1.2.0
    - ipython>=6.5.0,<6.5.1
    - jupyter>=1.0.0,<1.1
    - joblib>=0.11,<0.12
    - matplotlib>=2.1.2,<2.2
    - nose>=1.3.7,<1.4
    - notebook>=5.7.2,<5.8
    - pandas>=0.23.4,<0.23.5
    - scikit-learn>=0.19.1,<0.19.2
    - seaborn>=0.9.0,<0.10.0
    - skll>=1.5,<1.6
    - statsmodels>=0.9.0,<0.9.1
    - sphinx
    - sphinx_rtd_theme
    - zeromq
    - coverage
    - parameterized
    - setuptools
    - openpyxl
    - xlrd
    - xlwt

  run:
    - python
    - numpy>=1.14.0,<1.15
    - scipy>=1.1.0,<1.2.0
    - ipython>=6.5.0,<6.5.1
    - jupyter>=1.0.0,<1.1
    - joblib>=0.11,<0.12
    - matplotlib>=2.1.2,<2.2
    - nose>=1.3.7,<1.4
    - notebook>=5.7.2,<5.8
    - pandas>=0.23.4,<0.23.5
    - scikit-learn>=0.19.1,<0.19.2
    - seaborn>=0.9.0,<0.10.0
    - skll>=1.5,<1.6
    - statsmodels>=0.9.0,<0.9.1
    - sphinx
    - sphinx_rtd_theme
    - zeromq
    - coverage
    - parameterized
    - openpyxl
    - xlrd
    - xlwt

test:
  # Python imports
  imports:
    - rsmtool
    - rsmtool.analyzer
    - rsmtool.comparer
    - rsmtool.configuration_parser
    - rsmtool.container
    - rsmtool.convert_feature_json
    - rsmtool.modeler
    - rsmtool.preprocessor
    - rsmtool.reader
    - rsmtool.reporter
    - rsmtool.test_utils
    - rsmtool.transformer
    - rsmtool.utils
    - rsmtool.writer

  commands:
    - rsmtool --help
    - rsmeval --help
    - rsmcompare --help
    - rsmpredict --help
    - rsmsummarize --help
    - render_notebook --help
    - convert_feature_json --help

about:
  home: https://github.com/EducationalTestingService/rsmtool
  license: Apache 2.0
