{% set data = load_setup_py_data() %}

package:
  name: rsmtool
  version: {{data.get('version')}}

source:
  path: ../../../rsmtool

build:
  number: 1
  noarch: python
  script:
    - cd $SRC_DIR
    - "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - rsmtool = rsmtool.rsmtool:main
    - rsmcompare = rsmtool.rsmcompare:main
    - rsmeval = rsmtool.rsmeval:main
    - rsmpredict = rsmtool.rsmpredict:main
    - rsmsummarize = rsmtool.rsmsummarize:main
    - render_notebook = rsmtool.reporter:main
    - convert_feature_json = rsmtool.convert_feature_json:main

{% block requirements -%}
requirements:
  build:
    - python >=3.6
    {% for req in data.get('install_requires', []) -%}
    - {{req.replace(">", " >").replace("<", " <").replace("==", " ")}}
    {% endfor %}
  run:
    - python >=3.6
    {% for req in data.get('install_requires', []) -%}
    - {{req.replace(">", " >").replace("<", " <").replace("==", " ")}}
    {% endfor %}
{%- endblock %}

test:
  # Python imports
  imports:
    - rsmtool
    - rsmtool.analyzer
    - rsmtool.comparer
    - rsmtool.configuration_parser
    - rsmtool.container
    - rsmtool.convert_feature_json
    - rsmtool.modeler
    - rsmtool.preprocessor
    - rsmtool.reader
    - rsmtool.reporter
    - rsmtool.test_utils
    - rsmtool.transformer
    - rsmtool.utils
    - rsmtool.writer

  commands:
    - rsmtool --help
    - rsmeval --help
    - rsmcompare --help
    - rsmpredict --help
    - rsmsummarize --help
    - render_notebook --help
    - convert_feature_json --help

about:
  home: https://github.com/EducationalTestingService/rsmtool
  license: Apache 2.0
  license_file: LICENSE
